### ISSUE TITLE
How can i download the VIPLMumoFace3K dataset

### ISSUE THREAD

**Issue by y352184741** [skgyu/CMOS-GAN#1]
Hi guys. Thanks for your great work on the HFR task. I am very interested in your dataset, namely VIPL-MumoFace-3K. But I can't find any link to download it.

**Comment by skgyu** [comment]
Thank you for being interested in our work. I will discuss the release of the dataset with all authors and make the dataset public as soon as possible.

**Comment by y352184741** [comment]
Thank you for your response! Wish you all the best！

**Comment by skgyu** [comment]
> Thank you for your response! Wish you all the best！

You can download the VIPL-MumoFace-2K Dataset from the following link:

https://vipl.ict.ac.cn/resources/databases/202309/t20230915_180574.html
